language: ruby
rvm:
  - 2.1.5
services: postgres
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database meeting_rooms_test;' -U postgres
  - bundle exec rake db:migrate
