default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  <% if ENV['USE_LINKED_DB'].present? %>
  host: db
  username: postgres
  <% end %>

development:
  <<: *default
  database: meeting_rooms_development

test:
  <<: *default
  database: meeting_rooms_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
